### ISSUE TITLE
[ProgressTracker] On Medium & Small size in disabled state the indicator is clipped on end and bottom sides

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#1027] opened 2024-03-14 15:19 UTC
To reproduce every steps that are disabled and are in small or medium size will have the following part of the indicator clipped

![image](https://github.com/adevinta/spark-android/assets/11772084/bb8249ae-7483-42b3-b237-67f08dda4a92)

**Comment by elisa-hery** [comment] 2024-05-14 15:31
@kazaky is on it

**Comment by kazaky** [comment] 2024-05-30 22:06
Hi @elisa-hery 
**For number 1:**
I couldn't reproduce, (Works on both phone & tablet) :)
Attached screenshots.

Would be nice if you added more details in such cases like (Phone model, API number, Android version)


**For number 2**

I fixed it in [this PR](https://github.com/adevinta/spark-android/pull/1146),
The root cause is actually this [ticket](https://github.com/adevinta/spark-android/issues/1080)

Thank you!



![Image](https://github.com/adevinta/spark-android/assets/4202132/a5e62350-d5fc-4605-99a6-f0f55e655961)
![Image](https://github.com/adevinta/spark-android/assets/4202132/4e5154b0-7418-4b7f-a158-5fea6c6c1f56)

**Comment by elisa-hery** [comment] 2024-06-07 10:27
@kazaky 
1. the issue occurs when we change font size, sorry I forgot to write it
2. the issue still occurs for me, even with the last app version I got :

![Image](https://github.com/adevinta/spark-android/assets/142396647/243b6dd9-d943-436c-accb-05872635ff21)

i'm moving this ticket back to dev (so that we don't forget to discuss it)

**Comment by kazaky** [comment] 2024-06-11 12:05
@elisa-hery : @soulcramer Knows the root of the issue, (need to change the font unit) from dp to sp
he shall sort it out

**Comment by elisa-hery** [comment] 2024-06-18 09:55
Status of the bugs : 
1. still in progress, @soulcramer is on it
2. examples crash, there is another ticket for that --> https://github.com/adevinta/spark-android/pull/1146

**Closed** 2024-06-24 14:56 UTC
Labels: Bug, Component

**Comment by elisa-hery** [comment] 2024-06-27 07:28
fixed ✅  I'm moving it to done



![Image](https://github.com/adevinta/spark-android/assets/142396647/65921725-04cd-41af-b85a-5251a20f5394)
